creator: !DatasetCBAStats
  inference: True
  model_name: "bigcode/starencoder"

transformer: !XGBTransformer
  drop_patterns:
    - "vcs_commit_sha"
    - "allure_id"
    - "test_file_path"
    - "test_method"
    - "unknown_files_count"
    - "test_case_id"
    - "_file_extension"
    - "_changed"
    - "_number_changes_14d"
    - "_number_changes_56d"
    - "test_content"
    - "code_diff"
  file_drop_patterns:
    - "_lines_added"
    - "_lines_deleted"
  file_features:
    - "number_changes_3d"
    - "number_changes_14d"
    - "number_changes_56d"
    - "distinct_authors"
    - "change_type"
    - "lines_added"
    - "lines_deleted"
    - "changed"
  preprocessing_files: False
  frequent_files_limit: 6000
  sparse: False
