creator: !AttentionCreator
  inference: True
  without_unstable: False
  path_inference: "inference/attention"
  embedding_dim: 32
  hidden_dim: 8
  output_dim: 1
  heads: 8
  device: "cpu"

transformer: !XGBTransformer
  drop_patterns:
    - "vcs_commit_sha"
    - "allure_id"
    - "test_file_path"
    - "test_method"
    - "unknown_files_count"
    - "test_case_id"
    - "cross_file_"
  file_drop_patterns:
    - "_number_changes_3d"
    - "_number_changes_14d"
    - "_number_changes_56d"
    - "_distinct_authors"
    - "_change_type"
    - "_lines_added"
    - "_lines_deleted"
    - "_changed"
  file_features:
    - "number_changes_3d"
    - "number_changes_14d"
    - "number_changes_56d"
    - "distinct_authors"
    - "change_type"
    - "lines_added"
    - "lines_deleted"
    - "changed"
  preprocessing_files: False
  frequent_files_limit: 6000
  sparse: False
